module.exports = [
  {
    name: "Görög joghurt (200g, zsírszegény)",
    calories: 130,
    protein: 20,
    lipids: 0.5,
    carbohydrate: 7,
    fiber: 0,
    natrium: 70,
  },
  {
    name: "Főtt tojás (2 darab)",
    calories: 155,
    protein: 13,
    lipids: 11,
    carbohydrate: 1,
    fiber: 0,
    natrium: 124,
  },
  {
    name: "Túró (200g, zsírszegény)",
    calories: 170,
    protein: 28,
    lipids: 4,
    carbohydrate: 6,
    fiber: 0,
    natrium: 400,
  },
  {
    name: "Fehérjepor shake (1 adag vízzel)",
    calories: 120,
    protein: 24,
    lipids: 1.5,
    carbohydrate: 2,
    fiber: 0,
    natrium: 150,
  },
  {
    name: "Pöttyös Protein Turó Rudi natúr",
    calories: 145,
    protein: 9.2,
    lipids: 8,
    carbohydrate: 13,
    fiber: 2.2,
    natrium: 24,
  },
  {
    name: "Milbona High Protein Cottage Cheese (250g)",
    calories: 225,
    protein: 32,
    lipids: 10,
    carbohydrate: 8,
    fiber: 0,
    natrium: 500,
  },
  {
    name: "Csirkemell (100g, sült)",
    calories: 165,
    protein: 31,
    lipids: 3.5,
    carbohydrate: 0,
    fiber: 0,
    natrium: 70,
  },
  {
    name: "Tonhal konzerv (100g, vízben)",
    calories: 110,
    protein: 25,
    lipids: 1,
    carbohydrate: 0,
    fiber: 0,
    natrium: 300,
  },
  {
    name: "Edamame (150g, héj nélküli)",
    calories: 190,
    protein: 17,
    lipids: 8,
    carbohydrate: 14,
    fiber: 8,
    natrium: 10,
  },
  {
    name: "Lencse (200g, főtt)",
    calories: 230,
    protein: 18,
    lipids: 1,
    carbohydrate: 38,
    fiber: 16,
    natrium: 4,
  },
];
